[package]
name = "rust_nes_esp"
version = "0.1.0"
edition = "2021"

[dependencies]
image = {version="0.25.5", optional=true}
clap = {version="4.5.32", features=["derive"]}

[dependencies.bitflags]
version = "2.8.0"